unstable_features = true
max_width = 120
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
combine_control_expr = false
wrap_comments = true
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
# required_version = "1.4.20"
space_after_colon = true
space_before_colon = false
space_before_fn_sig_paren = true
space_around_attr_eq = true
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
trailing_comma = "Always"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
# width_heuristics = "Scaled"
use_try_shorthand = true
where_single_line = true
preserve_block_start_blank_lines = false
