[package]
name = "rmnd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.17"
# regex = "1.6.0"
colored = "2.0.0"
toml = "0.5.9"
serde = "1.0.144"
serde_derive = "1.0.144"
text_io = "0.1.12"